### ISSUE TITLE
Error with simulation/gss/local/run_gss.sh stage 4  when saving enhanced cuts manifest to enhanced_manifest

### ISSUE THREAD

**Issue by MrSupW** [mispchallenge/MISP-2023-Challenge-Baseline#1]
All right with enhancing all audio by gss. But at last, it went wrong.
It seems that something is wrong with rywang99/gss.

![f175a37915f010edaf0058f925e2fee](https://github.com/mispchallenge/MISP-2023-Challenge-Baseline/assets/57617568/c242877d-ce3c-4082-8b81-b066aebe1b99)

**Comment by mispchallenge** [comment]
Hello, this error does not affect the results because the file (cuts_enhanced.jsonl.gz) generated in this step is not used in subsequent steps. In addition, I have made modifications in run_gss.sh, but verification takes time, so you don’t need to redo this step.
