### ISSUE TITLE
Error with asr/decode_asr.sh

### ISSUE THREAD

**Issue by mengjie-du** [mispchallenge/MISP-2023-Challenge-Baseline#2]
I ran decode_asr.sh on Aishell1 test set and got the followed error:
`ValueError: --preencoder must be one of ('sinc', 'linear', None): --preencoder vggfeat`
Maybe you should release the class file containing **vggfeat** for convenience or mention the structure.

**Comment by mispchallenge** [comment]
Note that you are supposed to replace the directories named "espnet" and "espnet2" in your customized Espnet package with the corresponding directories from the repository. We have made some fixes in our codes.

**Comment by mispchallenge** [comment]
https://github.com/mispchallenge/MISP-ICME-AVSR/tree/master

**Comment by mengjie-du** [comment]
Thank you!
